spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:


  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ca80f14a6e6b6c34ea821c46af0cc10c
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: gender, age_range, birthday
            client-name: kakao

          naver:
            client-id: DlnbhpvSk3xCo23xuois
            client-secret: zjUwJfFK8W
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: gender, age_range, birthday
            client-name: naver


        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


jwt:
  secret: s1BttUnQn57UZmhAynlWa85Dvk0qnzu9sa12Bhdfu31mASDr9uB40AS9ureDwj12rS4jdiofq0u


file:
  dir: src/test/java/Project/OpenBook/TestImage
